# Generated by Django 5.0.6 on 2024-06-18 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="project title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="project description")),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, verbose_name="email address")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("is_new_password", models.BooleanField(default=True, verbose_name="is new password")),
                ("username", models.CharField(blank=True, max_length=150, null=True, verbose_name="username")),
                ("phone_number", models.CharField(blank=True, max_length=15, null=True, verbose_name="phone number")),
                ("service_name", models.CharField(max_length=50, verbose_name="service name")),
                ("login_url", models.URLField(blank=True, null=True, verbose_name="login url")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="credentials", to="project.project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="task title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="task description")),
                ("remind_at", models.DateTimeField(blank=True, null=True, verbose_name="remind at")),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="project.project"
                    ),
                ),
            ],
        ),
    ]
