repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --settings ./account_manager/pyproject.toml .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: black
        name: black
        entry: black --config ./account_manager/pyproject.toml .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 --toml-config ./account_manager/pyproject.toml .
        language: system
        types: [ python ]
        pass_filenames: false
