repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --settings ./account_manager/pyproject.toml .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: black
        name: black
        entry: black --config ./account_manager/pyproject.toml .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 --toml-config ./account_manager/pyproject.toml .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: docker-compose -f ./account_manager/docker-compose.yml run --rm test pytest
        language: system
        pass_filenames: false
        types: [ python ]
        args: [ "--cov=.", "--cov-report=html" ]
