# Generated by Django 5.0.6 on 2024-06-03 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_add_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='username')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number')),
                ('service_name', models.CharField(max_length=50, verbose_name='service name')),
                ('login_url', models.URLField(blank=True, null=True, verbose_name='login url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('local_id', models.PositiveIntegerField(blank=True, editable=False)),
                ('title', models.CharField(max_length=255, verbose_name='project title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='project description')),
                ('credentials', models.ManyToManyField(blank=True, to='accounts.credential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.PositiveIntegerField(blank=True, editable=False)),
                ('title', models.CharField(max_length=255, verbose_name='task title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='task description')),
                ('remind_at', models.DateTimeField(blank=True, null=True, verbose_name='remind at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='accounts.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to='accounts.task'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('project', 'local_id'), name='unique_local_id_per_project'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_slug_per_user'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('user', 'local_id'), name='unique_local_id_per_user'),
        ),
    ]
