# Generated by Django 5.0.6 on 2024-05-31 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_project_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='reminder description')),
                ('remind_at', models.DateTimeField(verbose_name='remind at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_set', to='accounts.project')),
                ('to_user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
