version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/database
    healthcheck:
      test: [ "CMD-SHELL", "psql -U ${POSTGRES_USER} -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: account_manager:latest
    container_name: app
    depends_on:
      postgres:
        condition: service_healthy
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${DJANGO_PORT}"
    ports:
      - ${DJANGO_PORT}:8000
    volumes:
      - ./:/code/
      - app-logs:/var/log/app

  test:
    image: account_manager:latest
    container_name: test
    depends_on:
      postgres:
        condition: service_healthy
    command: /bin/bash -c "python manage.py migrate && pytest"
    volumes:
      - ./:/code/

volumes:
  db-data: { }
  db-logs: { }
  app-logs: { }
